name: djmobilapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  webview_flutter: ^4.11.0
  just_audio: ^0.9.34
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  image_picker: ^0.8.7+3
  http: ^0.13.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/your_logo.png
    - assets/default_profile.png
    - assets/default_music.jpg
    - assets/music1.png
    - assets/music2.png
    - assets/music3.png
    - assets/music4.png
